// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://derxokstywhlpjsrxonl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlcnhva3N0eXdobHBqc3J4b25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODgxODcsImV4cCI6MjA2MjI2NDE4N30.QbYepK75AHA5pGIfJtJbceQUIdQP1M0FRPPH2SDYiAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);